<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><title></title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=320, target-densitydpi=device-dpi">
        <style type="text/css">
            body { width: 100% !important; background-color: #fff; 
                   margin: 0; padding: 0; 
                   font-family: HelveticaNeue, sans-serif; 
            }
            table.content { width:500px; margin: 0 auto; padding: 10px; 
                            border-left:0px solid #333; border-right:0px solid #333; }
            table td, table tr { border-collapse: collapse; }
            p { line-height: 1.8em; }
            img { outline: none; text-decoration: none; display: block;}
            br, strong br, b br, em br, i br { line-height:100%; }
            h1, h2, h3, h5, h6 { line-height: 100% !important; -webkit-font-smoothing: antialiased; color:#fff }
            h4 { line-height: 100% !important; -webkit-font-smoothing: antialiased; color:#000 }
            h1 a, h2 a, h3 a, h4 a, h5 a, h6 a { color: #fff !important; }
            #bck-orange { background-color: #FF6501; }
            #footer { border-radius:0px 0px 6px 6px; -moz-border-radius: 0px 0px 6px 6px; 
                      -webkit-border-radius:0px 0px 6px 6px; 
                      -webkit-font-smoothing: antialiased; }
            
            /* Fonts and Content */
            .header-content { font-size: 13px; color: #FFF; padding: 10px; text-align: center;
                              border-radius:10px 10px 0px 0px; -moz-border-radius: 10px 10px 0px 0px; 
            }
            .header-content h4 { color: #FFF;  
            }
            #content-mail { padding: 10px 10px 20px 40px; font-size: 11px; color:#333; height: auto; 
                            border-left:1px solid #FF6501; border-right:1px solid #FF6501;
            }
            #footer { background-color: #FF6501; color: #fff; margin-top: 0px; padding: 10px; font-size: 10px; text-align: center }
            #footer a { color: #ede899; text-decoration: none; font-weight: bold; }
            
        </style>
        
        
    <body>
        <table class="content" cellpadding="0" cellspacing="0">
            <tr>
                <td>
                    <div class="header-content" id="bck-orange">
                        <h3> CGECI </h3>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div id="content-mail">                    
                        <?php echo $this->layout()->content; ?> 
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div id="footer">
                        ceci est un mail automatique, veuillez ne pas y répondre
                    </div>
                </td>
            </tr>
        </table>
    </body>   
        