
<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-user"></i> Membres en attente de validation</h2>
            <div class="box-icon">
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
            </div>
        </div>
        
</div><!--/row-->


<!-- LISTE DES MEMBRES  -->
<?php if(isset($this->members)) : ?>
<div class="row-fluid sortable">
    <div class="box span12">
        <?php if(count($this->members)) { ?>
          <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
              <thead>
                      <tr>
                            <th>Membre</th>
                            <th>Date de naissance</th>
                            <th>Email</th>
                            <th>Mobile</th>
                            <th>Ville</th>
                            <th></th>
                      </tr>
              </thead> 
             
              <tbody>
                   <?php foreach($this->members as $m) : ?>
                    <tr>
                            <td> <?php echo $m['nom'].' '.$m['prenoms'];?> </td>
                            <td class="center"> <?php echo $m['date_naissance'];?> </td>
                            <td class="center"> <?php echo $m['email'];?> </td>
                            <td class="center"><?php echo $m['mobile'];?></td>
                            <td class="center"><?php echo $m['ville'];?></td>
                            <td class="center"><?php echo $m['ville'];?></td>
                            <td><a class="btn btn-info" href="#">
                                            <i class="icon-download icon-white"></i>  
                                            voir piece idendité                                            
                                </a> </td>                            
                    </tr>
                   <?php endforeach; ?>
              </tbody>
            </table>
          </div>
        <?php } else { ?>
            <div class="label label-warning"> Désolé aucun membre enregistré </div>
        <?php } ?>
    </div>
</div>
<?php endif; ?>

