
<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-edit"></i> Rechercher un membre </h2>
            <div class="box-icon">
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
            </div>
        </div>
        <div class="box-content">
            <form class="form-inline" method="POST">
                <fieldset>
                    <div class="control-group">
                        <label class="control-label" for="typeahead"></label>
                        <div class="controls">
                            <input type="text" class="span6" name="searchText" >
                            <!-- <p class="help-block">saisir les 1eres lettres du nom</p> -->
                        </div>
                    </div>
                    <div class="form-actionsss">
                        <button type="submit" class="btn btn-primary">rechercher</button>
                    </div>
                </fieldset>
            </form>   

        </div>
    </div><!--/span-->
</div><!--/row-->

<!-- RESULTATS -->
<?php if(isset($this->members)) : ?>
<div class="row-fluid sortable">
    <div class="box span12">
        <?php if(count($this->members)) { ?>
          <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
              <thead>
                      <tr>
                              <th>Membre</th>
                              <th>Compte</th>
                              <th>Email</th>
                              <th>Mobile</th>
                              <th>Statut</th>
                      </tr>
              </thead> 
             
              <tbody>
                   <?php foreach($this->members as $m) : ?>
                    <tr>
                            <td> <?php echo $m['nom'].' '.$m['prenoms'];?> </td>
                            <td class="center"> <?php echo $m['compte'];?> </td>
                            <td class="center"><?php echo $m['email'];?></td>
                            <td class="center"><?php echo $m['mobile'];?></td>
                            <td class="center">
                              <?php if($m['statut']==1) { ?> <span class="label label-success">Active</span> <?php } ?>
                              <?php if($m['statut']==0) { ?> <span class="label label-info">En attente</span> <?php } ?>
                              <?php if($m['statut']==2) { ?> <span class="label label-">Désactivé</span> <?php } ?>
                            </td>
                            <td class="center">
                                    <a class="btn btn-success" href="<?php echo $this->url(array('module'=>'backend', 'controller' => 'member', 'action' => 'detail', 'id'=>$m['id']), null, true); ?>">
                                            <i class="icon-zoom-in icon-white"></i>  
                                            accéder au détail                                            
                                    </a>
                                    <a class="btn btn-info" href="<?php echo $this->url(array('module'=>'backend', 'controller' => 'member', 'action' => 'downloadidentitycard', 'f'=>$m['piece_idendite']), null, true); ?>">
                                            <i class="icon-arrow-down icon-white"></i>  
                                            voir piece idendité                                            
                                    </a>
                                    <!-- <a class="btn btn-info" href="#">
                                            <i class="icon-edit icon-white"></i>  
                                            modifier                                            
                                    </a>
                                    <a class="btn btn-danger" href="#">
                                            <i class="icon-trash icon-white"></i> 
                                            supprimer
                                    </a> -->
                            </td>
                    </tr>
                   <?php endforeach; ?>
              </tbody>
            </table>
          </div>
        <?php } else { ?>
            <div class="label label-warning"> Désolé aucun membre ne correspond </div>
        <?php } ?>
    </div>
</div>
<?php endif; ?>

