
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Administration - CGECI</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/lib/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/lib/bootstrap/css/bootstrap-responsive.css">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <style type="text/css">
      body {
        padding-top: 80px;
        padding-bottom: 30px;
        background-color: #f5f5f5;
      }
      h3 {
          font-weight: normal;
      }
      .form-signin {
        max-width: 500px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid green;
        border-top:10px solid green;
        border-bottom:10px solid green;
        -webkit-border-radius: 15px;
           -moz-border-radius: 15px;
                border-radius: 15px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 30px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 12px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
        width: 185px;
      }
      img#logo {
          margin: 0 auto;
          padding: 0;
          width:200px;
          height:200px;
          margin-top:-25px;
      }
      #errorBlock {
          padding:5px; color:#FFF; 
          margin-bottom: 10px; background-color: #F00; 
          text-align: center
      }
      #loginBtn {
          height:38px;
          position:relative;
          top:-7px;
      }

    </style>
    
 </head>

  <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
  <!--[if IE 7 ]> <body class="ie ie7"> <![endif]-->
  <!--[if IE 8 ]> <body class="ie ie8"> <![endif]-->
  <!--[if IE 9 ]> <body class="ie ie9"> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> 
  <body> 
  <!--<![endif]-->
    
    <?php echo $this->layout()->content; ?>
 
    <!-- Le javascript 
    ================================================ -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?php echo $this->baseUrl(); ?>/lib/bootstrap/js/bootstrap.js"></script>

  </body>
</html>

