<div class="navbar">
    <div class="navbar-inner">
        <ul class="breadcrumb">
            <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
            <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
            
            <?php if(in_array($this->controller, array('action', 'op'))) :?>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'action', 'action' => 'list')); ?>">
                        actions</a> <span class="divider">/</span>	
                </li>
                <li>
                    <a href="#">détails</a> <span class="divider">/</span>	
                </li>                
            <?php endif; ?>
            
            <li>
                <a href="#">Settings</a> <span class="divider">/</span>	
            </li>
            
            <li class="active">Tools</li>
        </ul>
    </div>
</div>
