<div id="header">
    
    <img src="<?php echo $this->baseUrl(); ?>/images/header.jpg" />
    <div id="userConnected" class="">
       <h5> Espace <br>Administration <br>CGECI </h5>
            <p>
                <?php echo $this->userLoggedIn['customer']; ?>
            </p>
            <p>
                <?php echo $this->userLoggedIn['company']; ?>
            </p>
            
   </div>
    
</div>