            <h4>Modification Coordonnées Société </h4>            
            <p>
                Raison sociale : <strong><?php echo $this->infoMail['company']; ?></strong>   <br/>
                Effectué par : <strong><?php echo $this->infoMail['doBy']; ?></strong>   <br/>
            </p>            
            <p> 
                <em>veuillez vous connecter au BackOffice pour plus de détails</em>
            </p>
            