
            <h4>Votre demande d'adhésion a été enregistrée avec succès</h4>            
            <p>
                Adhérent : <strong><?php echo $this->infoMail['subscriber']; ?></strong>   <br/>
                Login : <strong><?php echo $this->infoMail['login']; ?></strong>   <br/>
                Mot de passe : <strong> celui saisi lors de votre inscription</strong>   <br/>
            </p>            
            <p> 
                <em>veuillez vous connecter au BackOffice pour plus de détails</em>
            </p>
            