            <h4>Demande d'inscription evenement </h4>            
            <p>
                Evenement : <strong><?php echo $this->infoMail['evenement']; ?></strong>   <br/>
                Raison sociale : <strong><?php echo $this->infoMail['company']; ?></strong>   <br/>
                Effectué par : <strong><?php echo $this->infoMail['doBy']; ?></strong>   <br/>
            </p>            
            <p> 
                <em>veuillez vous connecter au BackOffice pour plus de détails</em>
            </p>
            