            <h4>Mot de passe oublié ? </h4>            
            <p>
                Client : <strong><?php echo $this->infoMail['user']; ?></strong>   <br/>
                Mot de passe : <strong><?php echo $this->infoMail['password']; ?></strong>   <br/>
            </p>            
            <p> 
                <em>Ceci est un mail automatique, veuillez ne pas y répondre</em>
            </p>
            