            <h4>Enregistrement d'un nouvel adhérent </h4>            
            <p>
                Client : <strong><?php echo $this->infoMail['user']; ?></strong>   <br/>
                Raison sociale : <strong><?php echo $this->infoMail['company']; ?></strong>   <br/>
                Téléphone : <strong><?php echo $this->infoMail['phones']; ?></strong>   <br/>
                email : <strong><?php echo $this->infoMail['email']; ?></strong>   <br/>
            </p>            
            <p> 
                <em>veuillez vous connecter au BackOffice pour plus de détails</em>
            </p>
            