<div class="row-fluid">

<h4 id='titleView'> 
    <label class="label label-inverse"><?php echo count($this->salles);?> salles de formation disponible </label>
</h4>
             
     

<?php if(isset($this->fm)) : ?>
    <div class='alert alert-success'> <?php echo $this->fm; ?></div>
<?php endif; ?>
    
        <div class="span12">
            <div class="block-content collapse in">
                    <table class="table table-striped table-bordered list">
                        <thead> 
                            <tr> 
                                <th>Salle</th> 
                                <th>Description</th> 
                                <th>Cout</th> 
                            </tr> 
                        </thead> 
                        <tbody> 
                            <?php foreach ($this->salles as $item) : ?>
                            <tr> 
                                <td> <?php echo $item['nom']; ?> </td> 
                                <td> <?php echo $item['description']; ?> </td> 
                                <td> <?php echo $item['montant']; ?> </td> 
                            </tr> 
                           <?php endforeach; ?>
                        </tbody> 
                    </table>
                </div>
        </div>
    
        <span class="span9">
            <a href="<?php echo $this->url(array('controller' => 'training-room', 'action' => 'reservation'), null, true); ?>" class="btn btn-warning btn-small"> 
                effectuer une demande 
            </a>
            <a href="<?php echo $this->url(array('controller' => 'training-room', 'action' => 'my-resa'), null, true); ?>" class="btn btn-warning btn-small"> 
                mes demandes 
            </a>
        </span>
</div>



