<div class="row-fluid">

<h4 id='titleView'> 
    <label class="label label-inverse"><?php echo count($this->myResas);?> demandes enregistrées </label>
</h4>
             
     

<?php if(isset($this->fm)) : ?>
    <div class='alert alert-success'> <?php echo $this->fm; ?></div>
<?php endif; ?>
    
        <div class="span12">
            <div class="block-content collapse in">
                    <table class="table table-striped table-bordered list">
                        <thead> 
                            <tr> 
                            <th>Place</th> 
                            <th>Date</th> 
                            <th>Nb Jour</th>
                            <th>Nb heure</th>
                            <th>Service</th>
                            <th>Effectué le</th>                            
                            </tr> 
                        </thead> 
                <tbody> 
                        <?php foreach($this->myResas as $item) : ?>
                        <tr> 
                            <td> <?php echo $item['place']; ?> </td> 
                            <td> <?php echo $item['date_debut']; ?> </td> 
                            <td> <?php echo ($item['jour']); ?> </td> 
                            <td> <?php echo $item['heure']; ?> </td> 
                            <td> <?php echo $item['service']; ?> </td> 
                            <td> <?php echo Utils::formatDateToFr($item['created_at'],TRUE); ?> </td> 
                        </tr> 
                       <?php endforeach; ?>
                    </tbody>                     
                 </table>
                </div>
        </div>
    
        <span class="span9">
            <a href="<?php echo $this->url(array('controller' => 'training-room', 'action' => 'reservation'), null, true); ?>" class="btn btn-warning btn-small"> 
                effectuer une demande 
            </a>
        </span>
</div>



