<h4 id='titleView'> 
    <label class="label label-inverse"><?php echo count($this->usersList);?> inscription en attente </label>
</h4>

<?php if(isset($this->fm)) : ?>
    <div class='alert alert-success'> <?php echo $this->fm; ?></div>
<?php endif; ?>
    
<?php foreach ($this->usersList as $item) : ?>
    <div class="block-content collapse in">
        <table class="table table-striped table-bordered  list">
            <thead> 
                <tr> 
                    <th>nom</th> 
                    <th>prénoms</th> 
                    <th>société</th> 
                    <th>téléphone</th> 
                    <th>adresse</th> 
                    <th>email</th> 
                    <!-- <th>login</th> 
                    <th>enregistré le</th>  -->
                    <th></th>
                </tr> 
            </thead> 
            <tbody> 
                <?php foreach($this->usersList as $item) : ?>
                <tr> 
                    <td> <?php echo $item['firstname']; ?> </td> 
                    <td> <?php echo $item['lastname']; ?> </td> 
                    <td> <?php echo $item['company_name']; ?> </td> 
                    <td> <?php echo $item['phone_number']; ?> </td> 
                    <td> <?php echo $item['address']; ?> </td> 
                    <td> <?php echo $item['email']; ?> </td> 
                    <!-- <td> <?php echo $item['login']; ?> </td> 
                    <td> <?php echo Utils::formatDateToFr($item['created_date'], TRUE); ?> </td> -->
                    <td>
                        <a href="<?php echo $this->url(array('module'=> 'backend', 'controller' => 'subscriber', 'action' => 'validate', 'sid' => $item['id']), null, true); ?>" class="label label-success"> 
                            valider adhésion
                        </a>
                    </td> 
                </tr> 
               <?php endforeach; ?>
            </tbody> 
        </table>
    </div>
 <?php endforeach; ?>




