<h4 id='titleView'> 
    <label class="label label-inverse"><?php echo count($this->usersList);?> adhérents inscrits </label>
</h4>

<?php if(isset($this->fm)) : ?>
    <div class='alert alert-success'> <?php echo $this->fm; ?></div>
<?php endif; ?>
    
<?php foreach ($this->usersList as $item) : ?>
    <div class="block-content collapse in">
        <table class="table table-striped table-bordered list">
            <thead> 
                <tr> 
                    <th>Adhérent</th> 
                    <th>société</th> 
                    <th>téléphone</th> 
                    <th>adresse</th> 
                    <th>email</th> 
                    <th>Inscris le</th>
                </tr> 
            </thead> 
            <tbody> 
                <?php foreach($this->usersList as $item) : ?>
                <tr> 
                    <td> <?php echo $item['firstname'].' '.$item['lastname']; ?> </td> 
                    <td> <?php echo $item['company_name']; ?> </td> 
                    <td> <?php echo $item['phone_number']; ?> </td> 
                    <td> <?php echo $item['address']; ?> </td> 
                    <td> <?php echo $item['email']; ?> </td> 
                    <td> <?php echo Utils::formatDateToFr($item['created_date'],TRUE); ?> </td> 
                </tr> 
               <?php endforeach; ?>
            </tbody> 
        </table>
    </div>
 <?php endforeach; ?>




